### PR TITLE
tests: remove extra semicolon in macro

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by hebasto** [comment]
Where the `PRINT_BUF` macro is used?

**Comment by jonasnick** [comment]
@hebasto it was just added with #1205 and not used anywhere as it's intended for development and debugging (see https://github.com/bitcoin-core/secp256k1/pull/1205#issuecomment-1413364303 for the rationale).

**Comment by real-or-random** [comment]
Now I also realized that the current location of the macro and the function are not great because you can use them only in `tests.c` but not in the actual library... Sorry for that.

@jonasnick Can you move the macro and the function? I propose to move it to the top of `util.h`, which is included very early. This should do the trick.

**Comment by jonasnick** [comment]
@real-or-random good point. Moved to `util.h`.

**Review by real-or-random — APPROVED** [review]
utACK c4062d6b5d83572c1932f32003a7c0e901fffc23

**Review by hebasto — APPROVED** [review]
ACK c4062d6b5d83572c1932f32003a7c0e901fffc23, I have reviewed the code and it looks OK.

**Pull request merged**
