### PR TITLE
ecdsa adaptor sigs [WIP]

### PR DESCRIPTION
**Pull request by jesseposner**

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
This is really cool - thank you for taking it over.

The current consensus is that this library should focus on the demands of Bitcoin Core. Modules outside of that focus can go into the [libsecp-zkp fork](https://github.com/ElementsProject/secp256k1-zkp). I initially wrote this code on top of libsecp, because libsecp-zkp was not up-to-date with the most recent libsecp. But that's not the case anymore and we have mechanisms in place now to bring libsecp-zkp in sync. Therefore, I'd recommend to rebase on top of libsecp-zkp (which should be very straightforward) and open a PR there.

**Comment by jesseposner** [comment]
@jonasnick Thanks for the heads-up! I will re-open the PR in libsecp-zkp.

**Comment by T3enale** [comment]
Im learning alot but also trying to pick up on this third language.. gaming
n coding lingo prety hard to decod when ur new lol

**Comment by jesseposner** [comment]
https://github.com/ElementsProject/secp256k1-zkp/pull/117

**Review by stevenans9859 — APPROVED** [review]

**Pull request closed without merging**
