### PR TITLE
Fix insecure links

### PR DESCRIPTION
**Pull request by rex4539**

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Thanks. There are still quite a few more occurences of insecure `http://www.opensource.org/licenses/mit-license.php`. Did you skip them on purpose?

**Comment by rex4539** [comment]
Actually, yes. I was just fixing a downstream issue so I didn't check any other potential cases.

But I can do so.

**Comment by rex4539** [comment]
Alright, I fixed all cases, except the upstream macro.

**Review by jonasnick — COMMENTED** [review]
ACK 07aa4c70ffb96d21e496854f823c3ea3353b9086

**Comment by sipa** [comment]
ACK 07aa4c70ffb96d21e496854f823c3ea3353b9086. Verified all the modified links.

**Pull request merged**
