### PR TITLE
release cleanup: bump version after 0.3.1

### PR DESCRIPTION
**Pull request by jonasnick**
Based on #1266

### CODE REVIEW

**Comment by real-or-random** [comment]
Hm, should this re-add the `[Unreleased]` section to the changelog? I guess I shouldn't have removed it in the other PR by a strict reading of the docs (but I believe removing it is a bit nicer because then the topmost thing is the current release and not an empty/dummy section)? Happy to open a PR to improve the docs.

**Review by real-or-random — APPROVED** [review]
ACK c72d7d7ab74464c6f48ff038e32cf472aee7cdfc

**Comment by jonasnick** [comment]
> Hm, should this re-add the [Unreleased] section to the changelog?

Done

**Review by real-or-random — APPROVED** [review]
ACK 29e0992f07f1c5b043076ce6e2a59caafc2ec6a4

**Review by real-or-random — APPROVED** [review]
ACK 656c6ea8d8ec5b4f1fa91bc7f0a0ecd10c5cf5a0

**Pull request merged**
