### PR TITLE
Skip unrelated files when using `git archive`

### PR DESCRIPTION
**Pull request by hebasto**
An option for https://github.com/bitcoin-core/secp256k1/issues/1175:

```sh
$ git fetch origin pull/1287/head
$ git archive --output=libsecp256k1-PR1287.tar.gz FETCH_HEAD 
$ sha256sum libsecp256k1-PR1287.tar.gz 
6e6fd21afd935e572b138258f782fed60bb11fa88aa51a9866f10cca5d25c39c  libsecp256k1-PR1287.tar.gz
$ git archive --output=libsecp256k1-PR1287.zip FETCH_HEAD 
$ sha256sum libsecp256k1-PR1287.zip 
e108fc4902502640eee2cf4bb69501a494904c4dcd0763c072cc4acaed565861  libsecp256k1-PR1287.zip
```

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
In what sense are these files unrelated? Is it worth maintaining a list of files in .gitattributes that are "unrelated"?

Fwiw git archive is not deterministic:

```
❯ git fetch origin pull/1287/head && git archive --output=libsecp256k1-PR1287.tar.gz FETCH_HEAD && sha256sum libsecp256k1-PR1287.tar.gz
From github.com:bitcoin-core/secp256k1
 * branch              refs/pull/1287/head -> FETCH_HEAD
5df771480968b3ff3df53c2808284e855912f037fa2c206b35205ae856e2aa52  libsecp256k1-PR1287.tar.gz
❯ git archive --output=libsecp256k1-PR1287.zip FETCH_HEAD  && sha256sum libsecp256k1-PR1287.zip
7d7167119528c18710f8f5191e2a574405f016f17a7b520a970aca22afa8778e  libsecp256k1-PR1287.zip
```

**Comment by hebasto** [comment]
> In what sense are these files unrelated? Is it worth maintaining a list of files in .gitattributes that are "unrelated"?

From https://github.com/bitcoin-core/secp256k1/issues/1175#issue-1492956877:

> It's a bit silly to not include files like `.gitignore` and `.cirrus.yml`. I mean this is for devs of the library, you would want to have these files.

**Comment by hebasto** [comment]
> Fwiw git archive is not deterministic:

Hmm, that's unexpected (

[`git archive`](https://git-scm.com/docs/git-archive) uses the passed commit time as the modification time of each file in the archive. And `gzip` is deterministic as well.

What is the source of non-determinism in your opinion?

**Comment by real-or-random** [comment]
> From [#1175 (comment)](https://github.com/bitcoin-core/secp256k1/issues/1175#issue-1492956877):
> 
> > It's a bit silly to not include files like `.gitignore` and `.cirrus.yml`. I mean this is for devs of the library, you would want to have these files.

Maybe you just got my comment the wrong way around? I said, "it's silly NOT to include (...)", so I'm arguing to include the files in the archive! I think they belong to the repo. Even as a local developer without git, you could potentially be interested in what is run on CI or what the maintainers believe should be in `.gitignore` (and other tools such as ripgrep use `.gitignore`, etc...) Happy to hear arguments for the other direction, of course. :)

**Comment by real-or-random** [comment]
> My bad! Sorry.

No worries. :)

**Pull request closed without merging**
