### PR TITLE
Suppress unused variable warning in automated test

### PR DESCRIPTION
**Pull request by Lewuathe**
`max_scalar` is only used when OpenSSL test is disabled.

```c++
Running test/bitcoin-util-test.py...
  CC       src/tests-tests.o
src/tests.c:3487:32: warning: unused variable 'max_scalar' [-Wunused-variable]
    static const unsigned char max_scalar[32] = {
                               ^
1 warning generated.
```

relates to: https://github.com/bitcoin/bitcoin/pull/7653

### CODE REVIEW

**Comment by apoelstra** [comment]
This causes a a "mixed declarations and code error" when openssl is available.

Recommend instead adding another set of #ifdef guards around the original location of this variable definition.

**Comment by sipa** [comment]
Agree with @apoelstra.

**Comment by sipa** [comment]
@Lewuathe Feel like addressing @apoelstra's comment?

**Comment by apoelstra** [comment]
Superceded by #403

**Pull request closed without merging**
