### PR TITLE
JNI: fix use sig array

### PR DESCRIPTION
**Pull request by fingera**

### CODE REVIEW

**Comment by fingera** [comment]
https://github.com/bitcoin-core/secp256k1/blob/e34ceb333b1c0e6f4115ecbb80c632ac1042fa49/src/java/org/bitcoin/NativeSecp256k1Test.java#L137-L159
this is pub key tweak

**Comment by gmaxwell** [comment]
I hate it when I accidentally press the [72] key. 

This change looks fine, but please don't make inaccurate commit messages.

**Comment by gmaxwell** [comment]
Thanks for the update. Sorry for the slow response. While you're fixing this, can you also change the code to make use of the return values and not just silence ignoring them?

**Comment by sipa** [comment]
ACK 74e2dbd68e07f752ac326a578e3071f9efa55e55. This is clearly an improvement.

Feel free to address to comment, but the serialization should never fail as the output array is large enough for any ECDSA signature.

**Comment by real-or-random** [comment]
ACK 74e2dbd68e07f752ac326a578e3071f9efa55e55 I've read the code but haven't tested it

**Pull request merged**
