### PR TITLE
ECDH: output compressed point

### PR DESCRIPTION
**Pull request by chfast**

### CODE REVIEW

**Comment by fanatid** [comment]
Related: #352 #354

**Comment by chfast** [comment]
Oh, thank. Good to know it is not only my issue. Any final conclusions how the API should look like?

**Comment by gmaxwell** [comment]
It is generally unsafe to use the raw point for almost any application. Following our design principle of being hard to abuse, we should not provide a function that directly does so.

Instead, I think we can do is take a hasher function point, similar to how the signing takes a nonce function. Callers that need some other scheme for handling the nonce can pass a function pointer that accomplishes whatever they need, without creating an appearance that it's generally okay to use the raw point for ECDH.

There is a lot of reckless cryptography out there. We're not going to change that, but we also don't need to be a part of it.

**Comment by fanatid** [comment]
@gmaxwell IIRC I implemented hash function as argument in #354, but not receive any feedback... should I reopen that PR?

**Comment by chfast** [comment]
It doesn't matter for me which version it will be. Is the one with the callback is to be accepted? Is the callback parameters as in the #354 fine?

**Comment by sipa** [comment]
Closing in favor of #354.

**Pull request closed without merging**
