### PR TITLE
Document that infinity must not be passed to ecmult_const

### PR DESCRIPTION
**Pull request by real-or-random**

### CODE REVIEW

**Comment by real-or-random** [comment]
Related to #788.

**Comment by gmaxwell** [comment]
What happens if you pass in a point at infinity? :)

**Comment by gmaxwell** [comment]
Ah. Storage type doesn't currently encode infinities so the to precomputed tables have issues.  Other than that it looks like it takes a smaller change to fix infinity support, most of which is obviously more correct than not doing it.

**Comment by gmaxwell** [comment]
Unless I'm mistaken, ecmult isn't constant time with respect to the point input.  If so, it could just return infinity in this case. It would be a smaller diff and less weird-surface to handle for future users of the function.

**Comment by real-or-random** [comment]
> Unless I'm mistaken, ecmult isn't constant time with respect to the point input.

Oh that's a good point. I took the easy way because with constant-timeness in mind but yes, it's constant-time in the scalar only.

**Pull request closed without merging**
