### PR TITLE
ci: Remove quirk that runs dummy command after wineserver

### PR DESCRIPTION
**Pull request by real-or-random**
The underlying issue is now worked around in upstream, see https://github.com/mstorsjo/msvc-wine/issues/47 for details.

### CODE REVIEW

**Review by hebasto — APPROVED** [review]
ACK 3f675716ee6b78f37893ecddda4cbed50b7e2e0d, I have reviewed the code and it looks OK.

**Comment by hebasto** [comment]
Maybe rebase on top of the https://github.com/bitcoin-core/secp256k1/issues/1326?

**Comment by hebasto** [comment]
I took liberty to combine this PR into https://github.com/bitcoin-core/secp256k1/pull/1337.

**Comment by real-or-random** [comment]
Let me manually retrigger CI here. I could imagine Cirrus is confused and still uses the old image here for some reason.

**Comment by real-or-random** [comment]
> Let me manually retrigger CI here. I could imagine Cirrus is confused and still uses the old image here for some reason.

Ok, that didn't help.

**Comment by real-or-random** [comment]
Closing in favor of #1337.

**Pull request closed without merging**
