### PR TITLE
doc: Fix upper bounds + cleanup in field_5x52_impl.h comment

### PR DESCRIPTION
**Pull request by robot-dreams**
When reviewing #816 I noticed the upper bounds in the comment at the top of `field_5x52_impl.h` were off by 1 (see `fe_verify`). This PR fixes the upper bounds and also cleans up the comment along the way.

### CODE REVIEW

**Comment by real-or-random** [comment]
Maybe this is a good opportunity to add a similar comment to the 10x26 implementation (or one that refers to the 5x52 comment).

**Review by real-or-random — APPROVED** [review]
ACK bc7420fcba0c272d23650256e9fea3c12a3abbd3

#816 reminded me that it may be a good idea to document the max magnitudes. (They're checked in the code in `fe_verify` but that's hard to discover if you're not familiar with the code.) But I guess it's not trivial, see https://github.com/bitcoin-core/secp256k1/pull/1028#discussion_r762599882

**Comment by real-or-random** [comment]
nit: The comment could also mention the order of the limbs. `[0]` is the least significant limb though that's the natural choice.

**Comment by elichai** [comment]
ACK bc7420fcba0c272d23650256e9fea3c12a3abbd3
This is great! I spend a lot of time figuring out what are magnitudes and how the field arithmetic works exactly, so any doc improvements there are very welcome :)

**Review by real-or-random — COMMENTED** [review]
ACK 1287786c7a97eff520ffbd6b0d8b2f99dbfc6371

**Comment by real-or-random** [comment]
(I cancelled CI because this is blocking the other builds and the diff here is just in comments.)

**Pull request merged**
