### PR TITLE
use python3 print

### PR DESCRIPTION
**Pull request by fchapoton**

### CODE REVIEW

**Comment by gmaxwell** [comment]
This is sage code, not python.

**Comment by fchapoton** [comment]
sage is using now python3, since january 2020 and version 9.0. So this file is no longer working.

**Comment by real-or-random** [comment]
Thanks, looks good! 

I noticed that `secp256k1.sage` does not work either with the current sage. This should also be easy to fix. Feel free to add a commit or indicate here that you're not willing to do this (then we can do it in another PR).

**Comment by fchapoton** [comment]
Conversion to python3 is not an easy task. It usually requires care from somebody knowing the code.

**Comment by jonasnick** [comment]
Merged as part of #849

**Pull request closed without merging**
