### PR TITLE
cmake: Make installation optional

### PR DESCRIPTION
**Pull request by CyberTailor**
Useful for embedding secp256k1 in a subproject.

### CODE REVIEW

**Comment by real-or-random** [comment]
cc @hebasto @theuni

**Comment by hebasto** [comment]
> Useful for embedding secp256k1 in a subproject.

I've been thinking on the same. Just waiting with a PR as "cmake"-PR pile looks quite big for now :)

**Comment by real-or-random** [comment]
What's the rationale behind this? I guess if you're not using it as a subproject, you can simply omit `make install`, but that doesn't work in for subproject because there's only a single `make` invocation for the parent project?

**Comment by CyberTailor** [comment]
> What's the rationale behind this?

To call `add_subdirectory()` just for the static library, not installing it after.

> So if you `make install` the parent project, you'd automatically get `make install` here?

Yes, unless you use `EXCLUDE_FROM_ALL` option, but in that case you wouldn't also get tests.

**Comment by hebasto** [comment]
FWIW, I've been maintaining a [repo](https://github.com/hebasto/secp256k1-CMake-example) with usage examples since reviewing of https://github.com/bitcoin-core/secp256k1/pull/1113.

There is a ["subtree"](https://github.com/hebasto/secp256k1-CMake-example/tree/subtree) branch there.

There are two options to include a subtree:

- `add_subdirectory(src/secp256k1)` includes all subtree's targets into a project's default ones, including tests and an install target.
- `add_subdirectory(src/secp256k1 EXCLUDE_FROM_ALL)` does not include a subtree install target into a project's default ones. However, the parent project can call `install(TARGETS secp256k1)`.

Here is an [example](https://github.com/google/leveldb/blob/77d66aaf3edd6db0f1bfb4308fdc68c62fcc7bf6/CMakeLists.txt#L35) of a similar option in Google's LevelDB project:
```CMake
option(LEVELDB_INSTALL "Install LevelDB's header and library" ON)
```

**Comment by theuni** [comment]
I believe [PROJECT_IS_TOP_LEVEL](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) and friends were introduced to help with this type of logic?

> A boolean variable indicating whether the most recently called [project()](https://cmake.org/cmake/help/latest/command/project.html#command:project) command in the current scope or above was in the top level CMakeLists.txt file.

**Comment by hebasto** [comment]
> I believe [PROJECT_IS_TOP_LEVEL](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) and friends were introduced to help with this type of logic?

Indeed. For CMake 3.21+.

**Comment by real-or-random** [comment]
Concept ACK

> > I believe [PROJECT_IS_TOP_LEVEL](https://cmake.org/cmake/help/latest/variable/PROJECT_IS_TOP_LEVEL.html) and friends were introduced to help with this type of logic?
> 
> Indeed. For CMake 3.21+.

Would it be a good idea to make the default depend on `PROJECT_IS_TOP_LEVEL` if the cmake version is at least 3.21?

**Comment by real-or-random** [comment]
and needs rebase :)

**Review by real-or-random — APPROVED** [review]
utACK 47ac3d63cd5e00a2d50cb489461c8bc349d37912

**Review by hebasto — APPROVED** [review]
ACK 47ac3d63cd5e00a2d50cb489461c8bc349d37912, tested on Ubuntu 23.04.

**Comment by real-or-random** [comment]
> > Would it be a good idea to make the default depend on PROJECT_IS_TOP_LEVEL if the cmake version is at least 3.21?
> 
> Would prefer to see this done here, but no need to block this PR I guess.


To be honest, my current policy is to merge everything that has enough ACKs. We see stalled PRs way too often in this repo (I don't know if it's worse than in Core, but it's annoying.)  I'll add this as an item to #1235.

@CyberTailor Are you willing to work on this? :)

**Comment by CyberTailor** [comment]
Later, when 3.21 could be safely set as the minimum supported version

**Comment by hebasto** [comment]
> > Later, when 3.21 could be safely set as the minimum supported version
> 
> Oh, I think the suggestion is to wrap it in `if(CMAKE_VERSION VERSION_GREATER_EQUAL 3.21)`

See #1284.

**Comment by theuni** [comment]
> To be honest, my current policy is to merge everything that has enough ACKs. We see stalled PRs way too often in this repo (I don't know if it's worse than in Core, but it's annoying.) I'll add this as an item to #1235.

Thanks, this is really helpful. Will keep in mind while reviewing

**Comment by hebasto** [comment]
FWIW, another option that could be considered for such a use case is [`CMAKE_SKIP_INSTALL_RULES`](https://cmake.org/cmake/help/latest/variable/CMAKE_SKIP_INSTALL_RULES.html).

**Pull request merged**
