### PR TITLE
Add speck logo

### PR DESCRIPTION
**Pull request by real-or-random**
In preparation for the planned release (codename "Ivory Tower"), this adds a carnivore-style logo. "secpk" is an anagram of "Speck", the German word for bacon. The color of the fist is the orange used in the Bitcoin logo.

Preview:

Sample wallpaper rendering:

The logo is based on two CC0-licensed images:
 - https://commons.wikimedia.org/wiki/File:CookedBacon.jpg
 - https://www.kisscc0.com/clipart/raised-fist-computer-icons-fist-bump-art-power-fis-b5f82z/

The font is Quantico.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Concept ACK. I would have preferred unprocessed meet... though, let's go with this.

**Comment by cryptozeny** [comment]
Concept ACK

**Comment by FelixWeis** [comment]
Great logo. Full ACK!

**Comment by jonasnick** [comment]
Good idea! "Speck" also refers to marshmallow. That'd be more peaceful.

speck
using https://www.kisscc0.com/clipart/marshmallow-computer-icons-download-stick-figure-d-orpqv1/

**Comment by sipa** [comment]
@jonasnick Sure that's not a toilet paper roll? That would be appropriate, as it seems likely to overtake BTC as the currency of the future.

**Comment by real-or-random** [comment]
Postponing until Core has agreed on a rebranding, see https://github.com/bitcoin/bitcoin/pull/18489. Their decision may affect our choice of colors for example.

**Pull request closed without merging**
