### PR TITLE
build: Add workaround for automake 1.13 and older

### LINKED ISSUE #890: autogen failed on centos7(AC_PROG_CC cannot be called after AM_PROG_CC_C_O)
[rc@cos108]~/secp256k1-24d1656c328c932cd533f6f4bf80b345b6591f0d$sh autogen.sh
configure.ac:407: error: AC_PROG_CC cannot be called after AM_PROG_CC_C_O
build-aux/m4/ax_prog_cc_for_build.m4:38: AX_PROG_CC_FOR_BUILD is expanded from...
configure.ac:407: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: echo failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

### PR DESCRIPTION
**Pull request by real-or-random**
Fixes #890.

### CODE REVIEW

**Comment by real-or-random** [comment]
I used a Docker image to verify that this solves the problem on CentOS7. 

If anyone wants to check:

Run `docker run -it centos:7` and then
```
yum -y install automake git libtool

cd
git clone https://github.com/bitcoin-core/secp256k1 
cd secp256k1

./autogen.sh

git fetch origin pull/891/head
git checkout FETCH_HEAD
./autogen.sh
```

**Comment by hebasto** [comment]
A bit related note: https://github.com/bitcoin/bitcoin/pull/18290

**Review by jonasnick — COMMENTED** [review]
Can report that this doesn't break my setup at least (automake 1.16).

**Comment by michaelfolkson** [comment]
This PR builds fine on MacOS Big Sur, automake 1.16.3. Will need to move to my Linux machine to test automake versions 1.13 and older. brew doesn't seem to easily support installing old versions.

**Comment by real-or-random** [comment]
I think this is ready to merge with 
 - 4 reports that this does not break anything for automake > 1.13. (including https://github.com/bitcoin-core/secp256k1/issues/890#issuecomment-777088802) 
 - 2 reports that this solves a problem for automake <= 1.13 (again including the one in the linked issue)

But maybe someone could leave at least one ACK. :)

**Comment by michaelfolkson** [comment]
Reviewed the small code change and doesn't break my setup. I have no reason not to ACK this :)

ACK f329bba244264fb5f2c952c11e614987519d0dbc

**Pull request merged**
