### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by practicalswift**

### CODE REVIEW

**Comment by practicalswift** [comment]
How is `Tag_ABI_optimization_goals` used? Will fixing the typo have any consequence on the actual binary produced?

**Comment by sipa** [comment]
>  is everything after the @ comment text intended for humans only?

I believe so.

@laanwj Can you comment?

**Comment by laanwj** [comment]
> is everything after the @ comment text intended for humans only?

Yep

**Comment by sipa** [comment]
utACK 4c0f32ed51409b340da84dd3d3f91f66b4cb4643

**Pull request merged**
