### PR TITLE
Fix gen_context/ASM build on ARM

### PR DESCRIPTION
**Pull request by real-or-random**
Obsoletes #935.

### CODE REVIEW

**Comment by gmaxwell** [comment]
I will test now.

**Comment by gmaxwell** [comment]
ACK c8483520c9077905a1dc8b9adb88b6ea2a3bd9ef   looks good and works here. Undefign is kinda yuck, but it is already doing it and it's cleaner than the obvious alternatives.

**Comment by sipa** [comment]
utACK c8483520c9077905a1dc8b9adb88b6ea2a3bd9ef. I verified that building still works on ARM64, but without asm of course.

Mental note for something to add: there is no sanity checking in ./configure when --with-asm=arm is selected, so it "succeeds" on ARM64, but compilation fails of course.

**Comment by real-or-random** [comment]
> Mental note for something to add: there is no sanity checking in ./configure when --with-asm=arm is selected, so it "succeeds" on ARM64, but compilation fails of course.

In generally, this makes sense because `auto` is always the clever setting and setting a value explicitly just forces this value. Maybe we should rename simply rename the setting to `arm32`?

**Comment by sipa** [comment]
@real-or-random Well, I think even when forcing we can check whether the build environment we have supports that option (we do for x86_64). Renaming to arm32 makes sense.

**Pull request merged**
