### PR TITLE
Create secp256k1.spec

### PR DESCRIPTION
**Pull request by AliceWonderMiscreations**
RPM spec file for Fedora / RHEL / CentOS - builds on CentOS 7

### CODE REVIEW

**Comment by sipa** [comment]
I don't have much of an opinion on including distribution-specific build files in the repository.

@laanwj @theuni Opinions?

**Comment by AliceWonderMiscreations** [comment]
My current opinion is don't. At the time I wrote the spec file I didn't realize the library was going to be bundled inside bitcoin and assumed it was going to be an external build dependency.

**Comment by AliceWonderMiscreations** [comment]
Also at the time I wrote this spec file, there was an experimental php module that used the library. I was playing with the php module for a shopping cart system I was designing, but have since re-designed the system so that everything key generation is done completely separately from the php part and can be done with python.

So I don't need the ability to have this library separate from bitcoin and I doubt very many people do.

**Comment by sipa** [comment]
@AliceWonderMiscreations Ok, thank you!

**Pull request closed without merging**
