### PR TITLE
Replace gen_context.c with a Python implementation

### PR DESCRIPTION
**Pull request by sipa**
This removes the need for a separate native toolchain to build `gen_context`, and the issues around compilation options affecting one but not the other.

Alternative to #918.

### CODE REVIEW

**Comment by sipa** [comment]
Also submitted the test improvements separately as #920.

**Comment by apoelstra** [comment]
concept ACK. I think this would work well for rust-bitcoin.

**Comment by fanquake** [comment]
Concept ACK - ran into issues running gen_context when cross-compiling with mingw-w64 while having Wine installed.

**Comment by real-or-random** [comment]
@fanquake 

As an alternative, @roconnor-blockstream is working on extending gen_context in https://github.com/bitcoin-core/secp256k1/pull/956. The plan (in that PR or in a follow up PR) is to simply ship with precomputed headers then, which would removes the need for running gen_context (or python) entirely for all supported builds.

**Comment by real-or-random** [comment]
Closing in favor of #988 .

**Pull request closed without merging**
