### PR TITLE
secp256k1 benchmarking programs can now accept parameters

### PR DESCRIPTION
**Pull request by midnightmagic**
-c will vary the loop counter
-i will vary the iterations per-loop
-w will change the WINDOW_G table size setting at runtime (primary reason for patch)

### CODE REVIEW

**Comment by sipa** [comment]
I like the changes here, but am not too happy with the implementation.

There has been talk about getting rid of the globals, and explicitly initializating a context object. I think I'll go through with those changes first, and then get back to this.

**Comment by midnightmagic** [comment]
Anything I can help with, let me know.

**Comment by sipa** [comment]
@midnightmagic Will do; I'd like to get #208 in first.

**Comment by sipa** [comment]
Needs pretty significant rewriting now, but should be cleaner :)

**Comment by gmaxwell** [comment]
This would be good to see done, but I don't see a reason to keep it open when no one is currently working on it and the PR is so thoroughly out of date.  Closing without prejudice, anyone who wants to pick this up should feel free to do so.

**Pull request closed without merging**
