### PR TITLE
Update Makefile.am - use gcc for compiling

### PR DESCRIPTION
**Pull request by doged**
fixes https://github.com/bitcoin/bitcoin/issues/7261
fresh ubuntu install couldnt find gcc.

### CODE REVIEW

**Comment by theuni** [comment]
NACK. That defeats the purpose of CC_FOR_BUILD. Rather, we should verify that CC_FOR_BUILD can produce a valid binary during configure and exit with a proper error if not.

**Comment by sipa** [comment]
@theuni Can you suggest a solution then?

**Comment by theuni** [comment]
@sipa how about https://github.com/theuni/secp256k1/commit/1fecd7251ea16f41bd5a9324fa184fbca1befc17 ?

**Comment by laanwj** [comment]
This would hardcode using gcc for build? Definite NACK.

**Comment by sipa** [comment]
@theuni Looks good (theuni@1fecd72)

**Comment by sipa** [comment]
@theuni Feel like PR'ing the above commit?

**Comment by theuni** [comment]
@sipa Yes, will do.

**Comment by laanwj** [comment]
Closing in favor of #399

**Pull request closed without merging**
