### PR TITLE
Add signRecoverable to the JNI interface.

### PR DESCRIPTION
**Pull request by ademuri**
This returns the recovery id, in addition to the signature.

### CODE REVIEW

**Comment by ademuri** [comment]
Looks like this still needs some work. I'm travelling this week, so I'll look at it next week.

**Comment by ademuri** [comment]
This is ready for review now.

**Comment by sipa** [comment]
@greenaddress Feel like reviewing this?

**Comment by real-or-random** [comment]
Closing this because we removed the JNI bindings in #682.

**Pull request closed without merging**
