### PR TITLE
release cleanup: bump version after 0.3.2

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Comment by hebasto** [comment]
Add `## [Unreleased]` to `CHANGELOG.md`?

**Review by real-or-random — APPROVED** [review]
ACK 440cbce6f0361c2ef4261f3ad00ceeaf0f0645ee

**Comment by real-or-random** [comment]
> Add `## [Unreleased]` to `CHANGELOG.md`? (see #1268)

Ah, yeah. I'm fine with either. The github release links to Changelog on master, so not having it is a tiny bit nicer if you read it now. But then we need to include it with the next update to the Changelog.

**Review by hebasto — COMMENTED** [review]
ACK 95448ef2f8a162c06b9cd566ce935164b14c6840

**Review by real-or-random — APPROVED** [review]
ACK 95448ef2f8a162c06b9cd566ce935164b14c6840

**Pull request merged**
