### PR TITLE
bench_ecdh: fix call to secp256k1_context_create

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by apoelstra** [comment]
Confirmed that this is the only call to `context_create` in the codebase that does not use one of the new constants.

**Comment by FelixWeis** [comment]
tested, works

**Comment by peterdettman** [comment]
Oops, I had noted this as long ago as #363 and forgot to send a separate PR.

**Comment by apoelstra** [comment]
@sipa @gmaxwell This is a one-line patch -- can I get a quick ACK?

**Comment by sipa** [comment]
Quick ACK

**Pull request merged**
