### PR TITLE
Rename testrand functions to have test in name

### PR DESCRIPTION
**Pull request by sipa**
Suggested here: https://github.com/bitcoin-core/secp256k1/pull/808#discussion_r488871913

### CODE REVIEW

**Comment by real-or-random** [comment]
ACK a45c1fa63cb3020225d72049ef9c1cf300014795 diff looks good

**Comment by gmaxwell** [comment]
utACK

**Comment by elichai** [comment]
utATCK a45c1fa63cb3020225d72049ef9c1cf300014795

**Comment by real-or-random** [comment]
Urghs, Travis failed. I'll restart it.

I believe what happened here is: The travis build was started with before #821 was merged, with the travis matrix (with the env variables) taken from before #821. Then #821 was merged while the travis build was running. The valgrind jobs, which ran late, then merged this PR with the new master after #821, which has a new travis.sh file...

**Pull request merged**
