### PR TITLE
[RFC] Remove OpenSSL testing support

### PR DESCRIPTION
**Pull request by sipa**
This removes the ability to test against OpenSSL, as well as the OpenSSL verification benchmark.

The motivation is that OpenSSL 3 is deprecating part of the API used here (see #869), and I'm not sure it's worth maintaining. We do lose the fact that this is the only test that verifies randomly-generated cases against an independent implementation. On the other hand, there are tons of existing fixed tests now that test all kinds of edge cases already.

### CODE REVIEW

**Comment by real-or-random** [comment]
Hm yeah, this has a history. I'd probably be fine with removing this but when we last wanted to get rid of the OpenSSL tests (https://github.com/bitcoin-core/secp256k1/pull/635), the conclusion was that we rather want to replace it by some other implementation (https://github.com/bitcoin-core/secp256k1/issues/691). @elichai has two old PRs with different implementations (https://github.com/bitcoin-core/secp256k1/pull/738 and https://github.com/bitcoin-core/secp256k1/pull/641). Now there's also https://github.com/LLFourn/secp256kfun by @LLFourn, which would be another good option (but needs Rust).

I also suggested removing the benchmarks in https://github.com/bitcoin-core/secp256k1/issues/736. This issue didn't get a lot of feedback but I assume removing the benchmark is not controversial.

**Comment by gmaxwell** [comment]
This looks good to me.  Cross-testing is important, but introduction of a new one shouldn't block removal of won whos interface instability has become a maintenance burden (particularly when  the alternative proposals add a rust dependency, which I think is extremely unattractive).

**Review by real-or-random — CHANGES_REQUESTED** [review]
Concept ACK 

Now with #984, the tests even fail. This means that not only the API of OpenSSL has changed v3 but also the behavior. This makes the tests unsuitable for us. 

This PR should also remove this change to `Makefile.am` https://github.com/bitcoin-core/secp256k1/pull/735/files#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4af

**Comment by fanquake** [comment]
Concept ACK

**Comment by jonasnick** [comment]
I agree that cross-testing is useful. I don't see such a problem with adapting the code calling into a library after a major release. But fine with me to remove it for now. Since the alternatives for cross-testing have tradeoffs as well, the easiest solution may be to reintroduce openssl 3 at some point. Perhaps once it is more popular. I don't have easy access to v3 right now to play with it.

Another quick fix would be to check that `OPENSSL_VERSION_NUMBER` in the `AC_COMPILE_IFELSE` statement of `SECP_OPENSSL_CHECK` is less than 3.

The commit lgtm.

**Comment by sipa** [comment]
@real-or-random Added this:

```diff
 bench_verify_LDADD = libsecp256k1.la $(SECP_LIBS) $(SECP_TEST_LIBS) $(COMMON_LIB)
-# SECP_TEST_INCLUDES are only used here for CRYPTO_CPPFLAGS
-bench_verify_CPPFLAGS = $(SECP_TEST_INCLUDES)
 bench_sign_SOURCES = src/bench_sign.c
```

**Comment by luke-jr** [comment]
Could just restrict it to the older version of OpenSSL?

**Review by jonasnick — COMMENTED** [review]
ACK bc08599e776aff33c834ef829843ec5f629d1f39

**Review by Trinacristella — COMMENTED** [review]
I'm new to a bunch of this but I know I can succeed

**Pull request merged**
