### PR TITLE
Disable s390x build

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
Context for posteriority https://github.com/bitcoin-core/secp256k1/pull/839#issuecomment-718067741. Seems like the issue is that it doesn't start (no output). Do we know that this isn't just a spurious failure in that particular build?

**Comment by sipa** [comment]
It seems all of travis is stuck...

**Comment by real-or-random** [comment]
https://twitter.com/travisci/status/1321392609668046849

**Comment by real-or-random** [comment]
see https://github.com/bitcoin/bitcoin/issues/17802

**Pull request closed without merging**
