### PR TITLE
Make all non-API functions (except main) static

### PR DESCRIPTION
**Pull request by sipa**

### CODE REVIEW

**Review by real-or-random — COMMENTED** [review]
Totally not opposed to this but do we really care about this in bench/tests? And if yes, do you see any way to ensure we don't miss functions (in the future)?

**Review by real-or-random — APPROVED** [review]
Okay, agreed on both counts. 

utACK e03ef8655933d3e2b4830e7f8fe86deba820a073

**Review by hebasto — APPROVED** [review]
ACK e03ef8655933d3e2b4830e7f8fe86deba820a073.

On my Ubuntu 22.04 (x86_64), the resulted test and bench binaries are a bit smaller in size, except for the `bench_internal`, which is a bit larger.

**Comment by real-or-random** [comment]
(Fwiw, github indicated a merge conflict here (due to the renamed `src/cttime_tests.c`) but my local git auto-merged this cleanly without conflicts, and the merge results looks clean...)

**Pull request merged**
