### PR TITLE
Signed-digit multi-comb ecmult_gen algorithm

### PR DESCRIPTION
**Pull request by sipa**
A third iteration of the signed-digit multi-comb ecmult_gen algorithm (earlier attempts: #693, and #546 by Peter Dettman). Short summary:
* A new constant-time point multiplication algorithm with precomputation (so only used for multiply with G).
* Based on section 3.3 of https://eprint.iacr.org/2012/309 by Mike Hamburg.
* Configurable through two parameters: COMB_BLOCKS and COMB_TEETH
  * Currently only 3 predefined configurations reachable through ./configure (tables 2 kB, 22 kB, 86 kB). All three are included in precomputed_ecmult_gen.c and tested in CI. The 2 kB option is already comparable in speed with the current code.
  * Many more configurations can be reached by manually setting the macros. These are not tested.

Compared with the previous PR #693:
* Updated to the new static-precomputation-only model (#893).
* Just 3 curated configurations reachable through configure.
* Removed some optimizations that do not matter (much).
* Do blinding through an final correction add rather than an initial start point, which may later permit usage of incomplete addition formulae (#1051).
* The recoding of the input scalar to signed bit representation is done slightly differently, which needs fewer special cases.

### CODE REVIEW

**Comment by peterdettman** [comment]
Just out of curiosity, some perf. numbers (best Min of 3 `bench sign`, 64-bit, i7-9750H):

| branch | ecdsa_sign | schnorrsig_sign |
| --- | --- | --- |
| master | 29.5 | 23.1 |
| this PR | 25.6 | 19.2 |
| experimental | 23.8| 17.7 |

("experimental" is this PR plus the other PRs for normalize, group formulae, and the "vector" modinv).

**Comment by sipa** [comment]
@peterdettman Care to redo benchmarks for the latest commit (I've removed the incomplete comb optimization, and re-added the uint32_t[9] recoded approach)?

**Comment by siv2r** [comment]
These were the best min I got (running the benchmark thrice) on my machine (64-bit, i7-8750H).

| branch | ecdsa_sign | schnorrsig_sign |
|-----------|-----------------|-----------------------|
| master |      64.4       |         49.6            |
| this PR|       57.0       |         42.0          |

**Comment by peterdettman** [comment]
Updated perf. numbers (best Min of 3 `bench sign`, 64-bit, i7-9750H):

| branch | ecdsa_sign | schnorrsig_sign |
| --- | --- | --- |
| master | 29.6 | 23.1 |
| this PR | 25.7 | 19.4 |
| experimental | 24.2| 17.9 |

("experimental" is this PR plus the other PRs for normalize, group formulae, and the "vector" modinv).

So this looks just slightly slower than before, but perfectly fine if we are merge-focused. We can go hunting the extra 2% once we've booked the 20%.

**Comment by sipa** [comment]
Restarting this in a new PR to avoid the WIP discussion: #1058.

**Pull request closed without merging**
