### PR TITLE
Fix infinity loop in secp256k1_schnorr_sign

### PR DESCRIPTION
**Pull request by fanatid**
[secp256k1_schnorr_sign](https://github.com/bitcoin-core/secp256k1/blob/7d15cd78599bdaeec72259e22a77bbad70c0428a/src/modules/schnorr/main_impl.h#L23) stop the loop only if [secp256k1_schnorr_sig_sign](https://github.com/bitcoin-core/secp256k1/blob/7d15cd78599bdaeec72259e22a77bbad70c0428a/src/modules/schnorr/schnorr_impl.h#L62)  return non-zero. But if secret key is zero `secp256k1_schnorr_sig_sign` will always [return zero](https://github.com/bitcoin-core/secp256k1/blob/7d15cd78599bdaeec72259e22a77bbad70c0428a/src/modules/schnorr/schnorr_impl.h#L70) and `secp256k1_schnorr_sign` never stops.

### CODE REVIEW

**Comment by apoelstra** [comment]
utACK. Note this also catches the case when the user passes the field order as secret key (which will also be interpreted as zero). I think this is a reasonably likely footgun to run into, especially because in many cases applications can accept secret keys from untrusted sources and not worry that anything will break.

Also note that `secp256k1_ecdsa_sign` has the same behaviour.

**Comment by fanatid** [comment]
@apoelstra I don't sure, but shouldn't we also check that secret key is less than field order?

**Comment by fanatid** [comment]
Updated.
I also changed [conditions order for nonce](https://github.com/bitcoin-core/secp256k1/blob/7d15cd78599bdaeec72259e22a77bbad70c0428a/src/modules/schnorr/main_impl.h#L46), because with `overflow` first makes check faster (`overflow` already exists, while for zero we should call function)

**Comment by fanatid** [comment]
ping :)

**Comment by sipa** [comment]
Needs rebase. Note that I plan to remove the Schnorr code in this repository, as it shouldn't be used for production use in its current form (and both API and signature compatibility will break before it's brough back).

**Comment by fanatid** [comment]
Rebased.
@sipa does it means that secp256k1 bindings (like [secp256k1-node](https://github.com/cryptocoinjs/secp256k1-node)) should not use Schnorr right now?

**Comment by sipa** [comment]
Nobody should use Schnorr as implemented now. It is an experiment, and
subject to change at any time (as the configure script will warn you about
if you try to enable it). The reason I want to remove it from the codebase
is because I keep hearing about people who want to use it for production,
so this is apparently not clear.

**Comment by fanatid** [comment]
Thank you for explanation.

**Comment by sipa** [comment]
No longer needed.

**Pull request closed without merging**
